### ISSUE TITLE
The hopper does not work properly when using ver_0.1.7

### ISSUE THREAD

**Issue by u7f8au7fbd** [AbdElAziz333/Canary#126]
The hopper does not function properly when connected to the composter.

**Comment by ZASebastian** [comment]
```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-04-20 19:56:28
Description: Ticking block entity

java.lang.ClassCastException: class net.minecraft.server.level.ServerLevel cannot be cast to class com.abdelaziz.canary.common.world.blockentity.BlockEntityGetter (net.minecraft.server.level.ServerLevel is in module minecraft@1.19.2 of loader 'TRANSFORMER' @535a518c; com.abdelaziz.canary.common.world.blockentity.BlockEntityGetter is in module canary@0.1.10 of loader 'TRANSFORMER' @535a518c)
	at net.minecraft.world.level.block.HopperBlock.updateHopper(HopperBlock.java:558) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:block.hopper.HopperBlockMixin,pl:mixin:A}
	at net.minecraft.world.level.block.HopperBlock.handler$bch000$updateBlockEntity(HopperBlock.java:550) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:block.hopper.HopperBlockMixin,pl:mixin:A}
	at net.minecraft.world.level.block.HopperBlock.m_6861_(HopperBlock.java) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:block.hopper.HopperBlockMixin,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60690_(BlockBehaviour.java:659) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:ai.pathing.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:block.flatten_states.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:util.block_tracking.BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.m_213563_(CollectingNeighborUpdater.java:132) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230645_(CollectingNeighborUpdater.java:78) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230660_(CollectingNeighborUpdater.java:65) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_214152_(CollectingNeighborUpdater.java:47) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.level.ServerLevel.m_46672_(ServerLevel.java:966) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.entity_movement_tracking.ServerLevelAccessor,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_6289_(ServerLevel.java:1431) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.entity_movement_tracking.ServerLevelAccessor,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6933_(Level.java:224) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46597_(Level.java:304) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
	at cofh.thermal.lib.block.entity.AugmentableBlockEntity.updateActiveState(AugmentableBlockEntity.java:176) ~[thermal_core-1.19.2-10.2.0.5.jar%23294!/:10.2.0.5] {re:classloading,pl:rei_plugin_compatibilities:B}
	at cofh.thermal.lib.block.entity.DynamoBlockEntity.tickServer(DynamoBlockEntity.java:117) ~[thermal_core-1.19.2-10.2.0.5.jar%23294!/:10.2.0.5] {re:classloading,pl:rei_plugin_compatibilities:B}
	at cofh.lib.api.block.entity.ITickableTile.lambda$createTicker$2(ITickableTile.java:49) ~[cofh_core-1.19.2-10.2.1.40.jar%23226!/:10.2.1] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.RebindableTickingBlockEntityWrapperAccessor,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.entity_movement_tracking.ServerLevelAccessor,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23281!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

```

**Comment by Tekunogosu** [comment]
Having this same issue. Using a hopper on a composter caused the server to crash. Seems to be pretty consistent too.

**Comment by u7f8au7fbd** [comment]
Hopper optimization has been added since 1.7, but this seems to be causing a lot of problems.

**Comment by AbdElAziz333** [comment]
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4549998) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550001) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550002) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4550004)

**Comment by u7f8au7fbd** [comment]
Thanks for the update. I am using MC_1.18.2 and had no problem with 1.8. But with the versions "0.1.7,0.1.9 , 0.1.10 , 0.2.0 , 0.2.1" I cannot make bone meal from the hopper connected to the composter.

**Comment by u7f8au7fbd** [comment]
All were run with Canary only configuration and the same results appeared. There is little possibility of incompatibility with other optimization mods.
