### ISSUE TITLE
Unknown incompatibility leads to changing piston state crashing the game

### ISSUE THREAD

**Issue by SiverDX** [AbdElAziz333/Canary#168]
1.19.2 - 0.2.8

I'm assuming this does not happen on a not-so-modded client
If the pistons are already in a activated state it's fine - but changing the state (to either extended or unextended) crashes the game

I did also find this: https://www.reddit.com/r/fabricmc/comments/12vuziu/game_crashes_when_piston_is_activated_due_to/

Deactivating `Canary` stops the crash from happening

latest.log
``` log
(...)
[01Aug2023 02:09:49.587] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.world.level.block.piston.PistonMovingBlockEntity
	at net.minecraft.world.level.block.piston.MovingPistonBlock.m_155881_(MovingPistonBlock.java:53) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.world.level.block.piston.PistonBaseBlock.m_8133_(PistonBaseBlock.java:188) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60677_(BlockBehaviour.java:653) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.level.ServerLevel.m_8698_(ServerLevel.java:1034) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.level.ServerLevel.m_8807_(ServerLevel.java:1021) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:287) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23839!/:?]
	... 5 more
```

[crash-2023-08-01_02.09.49-server.txt](https://github.com/AbdElAziz333/Canary/files/12223097/crash-2023-08-01_02.09.49-server.txt)

**Comment by SiverDX** [comment]
After loading into the world:

![image](https://github.com/AbdElAziz333/Canary/assets/22003703/1802ae6d-7f9a-48b1-9b6a-559d7ef46914)

Tried `alloc.enum_values.piston_block=false` in `canary.properties`, did not work:
`[01Aug2023 02:19:21.199] [main/WARN] [CanaryConfig/]: No configuration key exists with name 'alloc.enum_values.piston_block', ignoring`

**Comment by SiverDX** [comment]
Manually removing the entry `block.moving_block_shapes.PistonMovingBlockEntityMixin` works

Regarding the config - is the syntax I used wrong?
`block.moving_block_shapes.PistonMovingBlockEntityMixin=false` seems to be wrong

**Comment by SiverDX** [comment]
okay, `mixin.block.moving_block_shapes` was the correct one
