### ISSUE TITLE
Server freezes

### ISSUE THREAD

**Issue by KostromDan** [AbdElAziz333/Canary#180]
M-Tech modpack 1.7.0
Install canary(I've temprorary removed it)
Create world with seed -3531681273743420041, fly in this direction, randomly locating biomes with nature compass, after some time server will completely freeze.
![image](https://github.com/AbdElAziz333/Canary/assets/90044015/5e0f5fba-16f5-4afd-af51-ee566f7d53e8)
Crash will happen even without this actions, but I'm saying that I've done.
If we rejoin world, already crashed it will crash again less 1 minute.
Removing Canary fixes problem.
Removing Smooth Chunks with enabled canary doesn't fix problem,.
[crash-2023-11-07_03.55.59-server.txt](https://github.com/AbdElAziz333/Canary/files/13274557/crash-2023-11-07_03.55.59-server.txt)

**Comment by kuba26038** [comment]
experiencing a very similar issue, but can't reproduce it so effectively

[crash-2023-11-04_19.25.30-server.txt](https://github.com/AbdElAziz333/Canary/files/13288903/crash-2023-11-04_19.25.30-server.txt)

**Comment by KostromDan** [comment]
> experiencing a very similar issue, but can't reproduce it so effectively
> 
> [crash-2023-11-04_19.25.30-server.txt](https://github.com/AbdElAziz333/Canary/files/13288903/crash-2023-11-04_19.25.30-server.txt)

add https://www.curseforge.com/minecraft/mc-mods/fullstack-watchdog and try to reproduce it again, by default vanilla cuts off the needed information in the crash report

for me reason is:
```
"Worker-Main9" daemon prio=1 Id=148 WAITING on java.util.concurrent.CompletableFuture$Signaller@47326b1d
	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.CompletableFuture$Signaller@47326b1d
	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3449)
	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3432)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:113)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6522_(Level.java:179)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6325_(Level.java:174)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_8055_(Level.java:352)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.LevelReader.m_46855_(LevelReader.java:153)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_6914_(Mob.java:806)
	at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.entity.EntityElephant.canSpawnWithTraderHere(EntityElephant.java:996)
	at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.event.ServerEvents.onEntityJoinWorld(ServerEvents.java:494)
	at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.event.__ServerEvents_onEntityJoinWorld_SpecialSpawn.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus$$Lambda$4392/0x00000008016fae78.invoke(Unknown Source)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.2/net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(ForgeEventFactory.java:201)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$addEntitiesToWorld$5(StructureTemplate.java:423)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$$Lambda$35076/0x00000008041b1fd8.accept(Unknown Source)
	at java.base@17.0.6/java.util.Optional.ifPresent(Optional.java:178)
```

**Comment by KostromDan** [comment]
Since alex mobs haven't been updated since 2022, and we recently started experiencing this glitch, I made a comparison across two versions of my modpack. The previous one didn't have this problem.
![image](https://github.com/AbdElAziz333/Canary/assets/90044015/00f10678-3de4-40f4-b633-3220074e0b5c)

**Comment by KostromDan** [comment]
For my modpack reproduction is:
1. seed: -3531681273743420041
2. /tp 100 150 -5300
3. freeze

**Comment by KostromDan** [comment]
Initially thought that Canary causes this, but it only increased chance of this problem.

**Comment by kuba26038** [comment]
> > experiencing a very similar issue, but can't reproduce it so effectively
> > [crash-2023-11-04_19.25.30-server.txt](https://github.com/AbdElAziz333/Canary/files/13288903/crash-2023-11-04_19.25.30-server.txt)
> 
> add https://www.curseforge.com/minecraft/mc-mods/fullstack-watchdog and try to reproduce it again, by default vanilla cuts off the needed information in the crash report
> 
> for me reason is:
> 
> ```
> "Worker-Main9" daemon prio=1 Id=148 WAITING on java.util.concurrent.CompletableFuture$Signaller@47326b1d
> 	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
> 	-  waiting on java.util.concurrent.CompletableFuture$Signaller@47326b1d
> 	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
> 	at java.base@17.0.6/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
> 	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3449)
> 	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3432)
> 	at java.base@17.0.6/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
> 	at java.base@17.0.6/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:113)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6522_(Level.java:179)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6325_(Level.java:174)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_8055_(Level.java:352)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.LevelReader.m_46855_(LevelReader.java:153)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_6914_(Mob.java:806)
> 	at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.entity.EntityElephant.canSpawnWithTraderHere(EntityElephant.java:996)
> 	at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.event.ServerEvents.onEntityJoinWorld(ServerEvents.java:494)
> 	at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.event.__ServerEvents_onEntityJoinWorld_SpecialSpawn.invoke(.dynamic)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus$$Lambda$4392/0x00000008016fae78.invoke(Unknown Source)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
> 	at TRANSFORMER/forge@43.3.2/net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(ForgeEventFactory.java:201)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$addEntitiesToWorld$5(StructureTemplate.java:423)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$$Lambda$35076/0x00000008041b1fd8.accept(Unknown Source)
> 	at java.base@17.0.6/java.util.Optional.ifPresent(Optional.java:178)
> ```
looks like a very useful mod to have. here's the same crash, this time with the mod:

[crash-2023-11-11_14.08.15-server.txt](https://github.com/AbdElAziz333/Canary/files/13325715/crash-2023-11-11_14.08.15-server.txt)

**Comment by kuba26038** [comment]
additionally, i can now say that the crash often occurs when a player joins the server. after this happens the server runs just fine

**Comment by KostromDan** [comment]
> additionally, i can now say that the crash often occurs when a player joins the server. after this happens the server runs just fine

We have different reasons.
for you reason is:
```java
"Server thread" prio=8 Id=157 TIMED_WAITING on java.lang.String@1d588f73
	at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.lang.String@1d588f73
	at java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_5667_(BlockableEventLoop.java:152)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:142)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.getChunkBlocking(ServerChunkCache.java:2262)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:2158)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6522_(Level.java:179)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6325_(Level.java:4049)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.PlayerRespawnLogic.m_183928_(PlayerRespawnLogic.java:23)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayer.m_9201_(ServerPlayer.java:272)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayer.<init>(ServerPlayer.java:246)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.players.PlayerList.m_215624_(PlayerList.java:407)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:138)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129483_(Connection.java:248)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
	-  locked java.util.Collections$SynchronizedRandomAccessList@53babb82
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer$$Lambda$34510/0x00007f11c37ec248.run(Unknown Source)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
	```

**Comment by KostromDan** [comment]
Try to find mod causing this by binary search.

**Comment by kuba26038** [comment]
> Try to find mod causing this by binary search.

i have no idea what that is, and googling it doesn't seem to give any results. could you please elaborate?
