### ISSUE TITLE
Crash on 1.19.3 Vanila Server

### ISSUE THREAD

**Issue by Toni-d-e-v** [AbdElAziz333/Canary#76]
---- Minecraft Crash Report ----
// My bad.

Time: 2022-12-29 13:28:50
Description: Unexpected error

net.minecraft.world.level.chunk.MissingPaletteEntryException: Missing Palette entry for index 0.
	at net.minecraft.world.level.chunk.LinearPalette.m_5795_(LinearPalette.java:75) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63085_(PalettedContainer.java:146) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:chunk.no_locking.PalettedContainerMixin,pl:mixin:APP:canary.mixins.json:chunk.serialization.PalettedContainerMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63087_(PalettedContainer.java:141) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:chunk.no_locking.PalettedContainerMixin,pl:mixin:APP:canary.mixins.json:chunk.serialization.PalettedContainerMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunkSection.m_63007_(LevelChunkSection.java:55) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:chunk.block_counting.LevelChunkSectionMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_62814_(LevelChunk.java:874) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.combined_heightmap_update.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelChunkMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_6425_(LevelChunk.java:189) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.combined_heightmap_update.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelChunkMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6425_(Level.java:365) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_233612_(ClientLevel.java:391) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104784_(ClientLevel.java:365) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1859) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1097) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:713) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[Forge%201.19.3.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Forge%201.19.3.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.level.chunk.LinearPalette.m_5795_(LinearPalette.java:75) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63085_(PalettedContainer.java:146) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:chunk.no_locking.PalettedContainerMixin,pl:mixin:APP:canary.mixins.json:chunk.serialization.PalettedContainerMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.PalettedContainer.m_63087_(PalettedContainer.java:141) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:chunk.no_locking.PalettedContainerMixin,pl:mixin:APP:canary.mixins.json:chunk.serialization.PalettedContainerMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunkSection.m_63007_(LevelChunkSection.java:55) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:chunk.block_counting.LevelChunkSectionMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_62814_(LevelChunk.java:874) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.combined_heightmap_update.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelChunkMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_6425_(LevelChunk.java:189) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.combined_heightmap_update.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelChunkMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6425_(Level.java:365) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_233612_(ClientLevel.java:391) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104784_(ClientLevel.java:365) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['tonidev'/424, l='ClientLevel', x=934.51, y=65.00, z=1003.90]]
	Chunk stats: 1681, 56
	Level dimension: minecraft:overworld
	Level spawn location: World: (3,106,-2), Section: (at 3,10,14 in 0,6,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1010807 game time, 949580 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:452) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[Forge%201.19.3.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Forge%201.19.3.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 420857912 bytes (401 MiB) / 872415232 bytes (832 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=31.0.12027.7000
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35766.00
	Virtual memory used (MB): 16053.30
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 550.58
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: Forge 1.19.3
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Radeon RX 570 Series GL version 3.2.0 Core Profile Context 22.20.27.07.221020, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.3-44.0.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.3-44.0.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.3-44.0.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.3-44.0.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.3-44.0.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		canary-mc1.19.3-0.1.4.jar                         |Canary                        |canary                        |0.1.4               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.3-44.0.0-universal.jar                 |Forge                         |forge                         |44.0.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: b74485fc-6582-41ad-9bfe-1b4307cfd8c4
	FML: 44.0
	Forge: net.minecraftforge:44.0.0

**Comment by AbdElAziz333** [comment]
can you test this (update)[https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.3-0.1.5-BETA]?
Please make sure to backup your world before updating!

**Comment by AbdElAziz333** [comment]
should be fixed in the new updates.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!
