### ISSUE TITLE
Last version resets my world [1.19.2]

### ISSUE THREAD

**Issue by pablonm5** [AbdElAziz333/Canary#79]
With last version my world regenerates all its chunks and removes all blocks except entities.
Thanks god i've made a backup! 😂

Before Update:  https://imgur.com/a/q1wZHby
After Update: https://imgur.com/a/kNRYT7Q

1.19.2 canary-mc1.19.2-0.1.5.jar

**Comment by supershorty1** [comment]
1.18.2 canary-mc1.18.2-0.1.1 having same problem

**Comment by EldrinFal** [comment]
Same here

**Comment by FanRenLa** [comment]
Again, if you replay the game save, all the changes you made are restored, the terrain is restored, and so are the blocks you placed.

**Comment by rrusciguy** [comment]
Just popping in to confirm. Any time you reload the world with v 0.1.5, the terrain and blocks are regenerated, but entities (at least the colonists for minecolonies in my limited testing) remain.

**Comment by ProfessorFartsalot** [comment]
This spams my console, too. I think I will stick with the other mod I use for this.


```

[08:07:35] [Server thread/ERROR] [minecraft/ChunkMap]: Couldn't load chunk [61, -27]
java.lang.NullPointerException: Cannot invoke "java.util.Optional.orElse(Object)" because the return value of "net.minecraft.world.entity.ai.village.poi.PoiManager.m_63818_(long)" is null
        at net.minecraft.world.entity.ai.village.poi.PoiManager.m_27047_(PoiManager.java:559) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:ai.poi.PoiManagerMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188230_(ChunkSerializer.java:117) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:A}
        at net.minecraft.server.level.ChunkMap.m_203107_(ChunkMap.java:543) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:550) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache.getChunkBlocking(ServerChunkCache.java:1769) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_ticking.ServerChunkCacheMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.ServerChunkCacheMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:1665) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_ticking.ServerChunkCacheMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.ServerChunkCacheMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_6522_(Level.java:169) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_46865_(Level.java:3073) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_46745_(Level.java:3068) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_7702_(Level.java:533) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:A}
        at mekanism.common.tile.component.TileComponentChunkLoader$ChunkValidationCallback.validateTickets(TileComponentChunkLoader.java:251) ~[Mekanism-1.18.2-10.2.5.465.jar%23110!/:10.2.5] {re:classloading}
        at net.minecraftforge.common.world.ForgeChunkManager.reinstatePersistentChunks(ForgeChunkManager.java:183) ~[forge-1.18.2-40.1.92-universal.jar%23181!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:491) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:173) ~[server-1.18.2-20220404.173914-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.DedicatedServerMixin,pl:mixin:A}
```

**Comment by lamoyrl90** [comment]
Thank god this issue has already been documented, saved me from binary search hell lol.
Canary 0.1.5, Minecraft 1.19.2, Forge 43.1.47

**Comment by NideVice** [comment]
Same problem with the world of creative and the world of the server
Canary 0.1.5, Minecraft 1.19.2, Forge 43.2.3
![image](https://user-images.githubusercontent.com/52417295/210438957-3ae8489c-8545-4ffa-b82c-fd8de4d42c33.png)
![image](https://user-images.githubusercontent.com/52417295/210439016-291acf4c-a19e-4967-b66f-08b2049d94cd.png)

**Comment by AbdElAziz333** [comment]
Sorry all, could you test the new versions?
[1.19.3](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.3-0.1.6) - [1.19.2](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-0.1.6) - [1.18.2](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.18.2-0.1.2)

**Comment by pablonm5** [comment]
> Sorry all, could you test the new versions? [1.19.3](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.3-0.1.6) - [1.19.2](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-0.1.6) - [1.18.2](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.18.2-0.1.2)




Seems fixed to me! Everything in place with the new version. Thanks!

**Comment by AbdElAziz333** [comment]
I hope you have a good day!

**Comment by lamoyrl90** [comment]
Yep, also works for me.
Thanks for the swift fix!
